version: '3.8'

networks:
  be-n:

services:
  # Api .NET
  lbt-api:
    container_name: lbt-api
    build: 
      context: ./LBT_Api
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${API_PORT_INSIDE}
    ports:
      - "${API_PORT_OUTSIDE}:${API_PORT_INSIDE}"
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
      ASPNETCORE_URLS: http://+:${API_PORT_INSIDE}
      MODE: Development
    networks:
      - be-n
  lbt-psql:
    container_name: lbt-psql
    build:
      context: ./Db
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
        - "${DB_PORT_OUTSIDE}:${DB_PORT_INSIDE}" 
    networks:
      - be-n