apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lbt-lbt-api
        resources:
        imagePullPolicy: Never
        ports:
        - containerPort: 2970
          name: api
        env:
        # DB_CONNECTION_STRING
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: lbt-secret
              key: db-connectionstring
        # ASPNETCORE_URLS
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: lbt-configmap
              key: api-urls
        # MODE
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: lbt-configmap
              key: api-mode
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: api

