apiVersion: v1
kind: Secret
metadata:
  name: lbt-secret
type: Opaque
data:
  # AdamDev
  postgres-user: QWRhbURldg==
  # AdamDev
  postgres-password: QWRhbURldg==
  # LBT_DB
  postgres-databasename: TEJUX0RC
  # Host=psql-db-service;Port=5600;Database=LBT_DB;Username=AdamDev;Password=AdamDev
  db-connectionstring: SG9zdD1wc3FsLWRiLXNlcnZpY2U7UG9ydD01NjAwO0RhdGFiYXNlPUxCVF9EQjtVc2VybmFtZT1BZGFtRGV2O1Bhc3N3b3JkPUFkYW1EZXY=
