CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Country" text NOT NULL,
    "City" text NOT NULL,
    "Street" text NOT NULL,
    "BuildingNumber" text NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE "ContactInfos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNumber" text NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_ContactInfos" PRIMARY KEY ("Id")
);

CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AddressId" integer NOT NULL,
    "Name" text NOT NULL,
    "SupplierId" integer NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Suppliers_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Suppliers_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
);

CREATE TABLE "Companys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AddressId" integer NOT NULL,
    "ContactInfoId" integer NOT NULL,
    "Name" text NOT NULL,
    "CompanyId" integer NULL,
    CONSTRAINT "PK_Companys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Companys_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Companys_Companys_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companys" ("Id"),
    CONSTRAINT "FK_Companys_ContactInfos_ContactInfoId" FOREIGN KEY ("ContactInfoId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierId" integer NOT NULL,
    "Name" text NOT NULL,
    "PriceNow" double precision NOT NULL,
    "ProductId" integer NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id"),
    CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Workers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "ContactInfoId" integer NOT NULL,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "WorkerId" integer NULL,
    CONSTRAINT "PK_Workers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Workers_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Workers_Companys_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companys" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Workers_ContactInfos_ContactInfoId" FOREIGN KEY ("ContactInfoId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Workers_Workers_WorkerId" FOREIGN KEY ("WorkerId") REFERENCES "Workers" ("Id")
);

CREATE TABLE "Sales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkerId" integer NOT NULL,
    "SaleDate" timestamp without time zone NOT NULL,
    "SumValue" double precision NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_Workers_WorkerId" FOREIGN KEY ("WorkerId") REFERENCES "Workers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductsSold" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "SaleId" integer NOT NULL,
    "AmountSold" integer NOT NULL,
    "PriceAtTheTimeOfSale" double precision NOT NULL,
    CONSTRAINT "PK_ProductsSold" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductsSold_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSold_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Companys_AddressId" ON "Companys" ("AddressId");

CREATE INDEX "IX_Companys_CompanyId" ON "Companys" ("CompanyId");

CREATE INDEX "IX_Companys_ContactInfoId" ON "Companys" ("ContactInfoId");

CREATE INDEX "IX_Products_ProductId" ON "Products" ("ProductId");

CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");

CREATE INDEX "IX_ProductsSold_ProductId" ON "ProductsSold" ("ProductId");

CREATE INDEX "IX_ProductsSold_SaleId" ON "ProductsSold" ("SaleId");

CREATE INDEX "IX_Sales_WorkerId" ON "Sales" ("WorkerId");

CREATE INDEX "IX_Suppliers_AddressId" ON "Suppliers" ("AddressId");

CREATE INDEX "IX_Suppliers_SupplierId" ON "Suppliers" ("SupplierId");

CREATE INDEX "IX_Workers_AddressId" ON "Workers" ("AddressId");

CREATE INDEX "IX_Workers_CompanyId" ON "Workers" ("CompanyId");

CREATE INDEX "IX_Workers_ContactInfoId" ON "Workers" ("ContactInfoId");

CREATE INDEX "IX_Workers_WorkerId" ON "Workers" ("WorkerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230516183149_wt___16_maj_2023_20_31_41', '7.0.5');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230516183218_wt___16_maj_2023_20_32_10', '7.0.5');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230516183256_wt___16_maj_2023_20_32_49', '7.0.5');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230516183519_wt___16_maj_2023_20_35_10', '7.0.5');

COMMIT;

